[2024-02-29T06:53:15.896+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.remove_airlines_file manual__2024-02-29T06:52:44.387615+00:00 [queued]>
[2024-02-29T06:53:15.919+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.remove_airlines_file manual__2024-02-29T06:52:44.387615+00:00 [queued]>
[2024-02-29T06:53:15.920+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-02-29T06:53:16.007+0000] {taskinstance.py:2214} INFO - Executing <Task(WasbDeleteBlobOperator): remove_airlines_file> on 2024-02-29 06:52:44.387615+00:00
[2024-02-29T06:53:16.017+0000] {standard_task_runner.py:60} INFO - Started process 199 to run task
[2024-02-29T06:53:16.021+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'AIRLINES_ETL_PIPELINE', 'remove_airlines_file', 'manual__2024-02-29T06:52:44.387615+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/AIRLINES_DATA_ETL_DAG.py', '--cfg-path', '/tmp/tmp_9gnbqq6']
[2024-02-29T06:53:16.025+0000] {standard_task_runner.py:88} INFO - Job 103: Subtask remove_airlines_file
[2024-02-29T06:53:16.130+0000] {task_command.py:423} INFO - Running <TaskInstance: AIRLINES_ETL_PIPELINE.remove_airlines_file manual__2024-02-29T06:52:44.387615+00:00 [running]> on host 586f09520b0e
[2024-02-29T06:53:16.764+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='AIRLINES_ETL_PIPELINE' AIRFLOW_CTX_TASK_ID='remove_airlines_file' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T06:52:44.387615+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T06:52:44.387615+00:00'
[2024-02-29T06:53:16.765+0000] {wasb_delete_blob.py:67} INFO - Deleting blob: Airlines_Data.csv.gz
 in wasb://raw
[2024-02-29T06:53:16.780+0000] {base.py:83} INFO - Using connection ID 'azure_blob_storage' for task execution.
[2024-02-29T06:53:17.838+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/microsoft/azure/operators/wasb_delete_blob.py", line 70, in execute
    hook.delete_file(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 529, in delete_file
    elif self.check_for_blob(container_name, blob_name):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 257, in check_for_blob
    self._get_blob_client(container_name, blob_name).get_blob_properties(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/azure/storage/blob/_blob_client.py", line 1370, in get_blob_properties
    process_storage_error(error)
  File "/home/airflow/.local/lib/python3.11/site-packages/azure/storage/blob/_shared/response_handlers.py", line 184, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
azure.core.exceptions.ClientAuthenticationError: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed
[2024-02-29T06:53:17.857+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=AIRLINES_ETL_PIPELINE, task_id=remove_airlines_file, execution_date=20240229T065244, start_date=20240229T065315, end_date=20240229T065317
[2024-02-29T06:53:17.987+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 103 for task remove_airlines_file (Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed; 199)
[2024-02-29T06:53:18.021+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-29T06:53:18.055+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
