[2024-02-22T08:55:21.497+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_random_quote manual__2024-02-22T08:54:57.397088+00:00 [queued]>
[2024-02-22T08:55:21.513+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_random_quote manual__2024-02-22T08:54:57.397088+00:00 [queued]>
[2024-02-22T08:55:21.513+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-22T08:55:21.917+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_random_quote> on 2024-02-22 08:54:57.397088+00:00
[2024-02-22T08:55:21.929+0000] {standard_task_runner.py:60} INFO - Started process 131 to run task
[2024-02-22T08:55:21.944+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_random_quote', 'manual__2024-02-22T08:54:57.397088+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmp1coy_7ks']
[2024-02-22T08:55:21.946+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask print_random_quote
[2024-02-22T08:55:22.710+0000] {task_command.py:423} INFO - Running <TaskInstance: welcome_dag.print_random_quote manual__2024-02-22T08:54:57.397088+00:00 [running]> on host 6281687bcd05
[2024-02-22T08:55:24.243+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_random_quote' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T08:54:57.397088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-22T08:54:57.397088+00:00'
[2024-02-22T08:55:24.246+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/welcome_dag.py", line 19, in print_random_quote
    response = requests.get(quote_api)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL "{{ var.value.get('quote_api') }}": No scheme supplied. Perhaps you meant https://{{ var.value.get('quote_api') }}?
[2024-02-22T08:55:24.508+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=welcome_dag, task_id=print_random_quote, execution_date=20240222T085457, start_date=20240222T085521, end_date=20240222T085524
[2024-02-22T08:55:24.777+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task print_random_quote (Invalid URL "{{ var.value.get('quote_api') }}": No scheme supplied. Perhaps you meant https://{{ var.value.get('quote_api') }}?; 131)
[2024-02-22T08:55:24.825+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-22T08:55:24.850+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
